#-------------------------------
# General Site Settings

title: Sergio Gualda
description: sgualda blog # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sgualda.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Sergio Gualda
author-avatar: perfil-sergio.jpg


#-------------------------------
# Contact links
#facebook:  https://facebook.com/ # Add your Facebook handle
twitter:   https://twitter.com/sgualda_ # Add your Facebook handle
instagram: https://www.instagram.com/montocode # Add your Facebook handle
#pinterest: https://www.pinterest.com/ # Add your Facebook handle
telegram: https://t.me/montocode/
linkedin: https://www.linkedin.com/in/sgualda/
email: contact.sgualda@gmail.com

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: https-sgualda-github-io # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: UA-111999870-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: b77ac09c85 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
